### ISSUE TITLE
When the PC has multiple NIC, how to send a request using the specified NIC?

### ISSUE THREAD

**Issue by jinnyu** [biuuu/genshin-wish-export#143]
env
NIC0 : Internet connect (10.0.0.40)
NIC1 : No internet connect, Intranet only. (10.0.1.2)

When enable proxy mode, software will chose NIC1 for proxy mode,
so that the software can not get response.

**Comment by PriceHu** [comment]
It shouldn't matter.

The proxy setting is more like a software level config which tells the system where to send network traffic. Basically it means your OS will wrap your network traffic with destination ip being the proxy server, and then send it out using whichever NIC you are mormally using. If you look closely into your system network config, you can see the software is using 127.0.0.1 as your proxy server, which is your local machine. The game will still use the NIC it normally uses, with just all network traffic go through the software. The software will show a worng `IP:port`, because it maybe just read from the first NIC from the system list. In my case the software shows my VirtualBox Host-Only Adapter address, which is at top of the NIC list, but the config actually points to `127.0.0.1`, and I can use it without problem.

In your case maybe it's a matter of operation order. Try open the software proxy mode first. When it shows using proxy mode `NIC IP:8325`, check your system proxy config to make sure it uses `127.0.0.1:8325`. Then go to open your game and open your gacha history. It should have no problem.

**Comment by jinnyu** [comment]
I figure out how to use `proxy mode` ,
Thank you~
